name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/2e2/*
jobs: 
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
        - name: Get code
          uses: actions/checkout@v4.2.2
          
        - name: Cypress run
          uses: cypress-io/github-action@v6.5.0
          with:
            install-dependencies: yarn install
            browser: electron
            record: true
            group: UI Electron
            spec: ${{ github.event.input.spec }}
          env:
            CYPRESS_RECORD_KEY: 1bfcd1ce-9fa3-445f-ae18-426e71b8840b
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
